apiVersion: kustomize.config.k8s.io/v1beta1
# Quais arquivos serão lidos?
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: devns
images:
- name: goserver
  newName: athirson010/gitopsfc
  newTag: newTag
