apiVersion: kustomize.config.k8s.io/v1beta1
# Quais arquivos serão lidos?
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: athirson010/gitopsfc
  newTag: 10def45be165979d0a65679e408bee19f803dda7
