apiVersion: v1
kind: Service
metadata:
  name: goserver-cluster-ip
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 80 #porta do serviço
      protocol: TCP
      targetPort: 80 #porta do container

#ClusterIP (padrão): os clientes internos enviam solicitações para um endereço IP interno estável.