apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef: #Referencia para a aplicacao
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
  minReplicas: 2 #min 2
  maxReplicas: 5
  #targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
